apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-app
  namespace: valaxy
spec:
  replicas: 2
  selector:
    matchLabels:
      app:  springboot-app
  template:
    metadata:
      labels:
        app:  springboot-app
    spec:
      imagePullSecrets:
      - name: jfrogcred 
      containers:
      - name:  springboot-app
        image: gedharizka/tweet-trend
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        