apiVersion: apps/v1
kind: Deployment
metadata:
  name: aku-laku-test-deployment
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: aku-laku-test
  template:
    metadata:
      labels:
        app: aku-laku-test
    spec:
      containers:
        - name: aku-laku-test
          image: gedharizka/tweet-trend:latest
