apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aku-laku-test-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: 146.190.5.20.aku.laku.test  # Ganti dengan IP Ingress Controller
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: aku-laku-test-service
            port:
              number: 8000